# Generated by Django 4.2.7 on 2024-04-09 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
